### ISSUE TITLE
Can't figure out what went wrong?

### ISSUE THREAD

**Issue by Psychogamer515** [FWDekker/fo4vr-modlist#19] opened 2024-05-24 01:22 UTC
Hello, thank you for the in-depth guide on how to get this working.

I am very dumb when it comes to this stuff but i really want to play this game in VR and be able to enjoy. I'm not really sure where I went wrong but the game wont load past the start screen after launching F4SEVR through MO2. There are also a few errors on MO2 that i don't know what they mean for the game.

I can share necessary info that would help to solve this if needed or even do screen share through Discord or something along those lines.

Any help will be appreciated
Thank You

**Comment by FWDekker** [comment] 2024-05-24 09:02
Hiya!

First things first, I think this issue might be related to UFO4P. It was recently updated because of the next-gen update for FO4, and I haven't yet had time to test out what combinations exactly work. However, I do know that the new v2.1.6 of UFO4P doesn't work with my guide, so you'll specifically need v2.1.5. So make sure you have that version.

As for the errors, could you share a screenshot?

Let me know if this works for you :-)

**Comment by Psychogamer515** [comment] 2024-05-24 19:38
Hello and thanks for getting back to me so soon,

I deleted the old UFO4P and also the patch and re-installed the versions
you mentioned, i tried launching the F4SEVR from MO2 after doing that and
still only got as far as the start screen. It loads a black screen with a
green vault-tec loading symbol after selecting new, also i had to for some
reason redo the settings in the start menu as mentioned in the guide. If
there is any more information that you need please let me know, like i said
in the issue post i just want to play the game and have fun. I really do
appreciate you taking the time to help me out with this.

Here are some screenshots that should help out

**Comment by FWDekker** [comment] 2024-05-24 22:03
It looks like your screenshots were lost in the process somehow; they are not included in your comment.

After starting a new game, do I understand correctly that you end up in an infinite loading screen, featuring a black background and the Vault-Tec loading screen? If so, what happens if you press the "confirm" button again (by which I mean the same button you press to select the "new" option in the main menu)? Does that help?

If not, I still suspect there might be some issues around non-VR FO4's next-gen patch and UFO4P, which I will investigate tomorrow. That said, if you get errors in MO2, I think that's the most important thing to figure out. Below I've written some relatively generic troubleshooting tips (which, now that I think about it, I should add as a separate section to my guide), written in descending order of likely relevance. But the errors and the "confirm" button are, I think, the most important leads right now.

---

If not, a few things you may want to check are (1) that your INI settings in MO2 are correct (see Section 3.2) (it is important that you edit the file in MO2), (2) that you have enabled (and sorted) your mods in the "Plugins" panel on the right-hand side, and (3) that you have downgraded and copied _all_ DLC from non-VR FO4 into FO4VR (because UFO4P _requires_ all DLC).

If that doesn't work, some files may have been corrupted. You can [verify integrity of game files of FO4VR in Steam](https://help.steampowered.com/en/faqs/view/0C48-FCBD-DA71-93EB), and then re-install `fo4vr_improvements` and `vrperfkit` (because Steam will overwrite part of those mods during integrity verification).

If that doesn't work: What happens if you launch FO4VR (without F4SEVR) through Steam and start a new game? Does that work? And if you disable all mods (without removing external libraries from Section 4.1) in MO2, and start F4SEVR through MO2? And if you remove external libraries from Section 4.1 as well, but still launch F4SEVR from MO2?

That's all the workarounds I can think of right now, without knowing too much about your specific issues.

**Comment by Psychogamer515** [comment] 2024-05-25 14:29
Sorry about the screenshots, I think you didn't receive the screenshots because i sent them through email in my last response let me try sending again through github.

You are correct, infinite loading screen, even if I press trigger again(same button i used to select new) sadly that does nothing new.

I'll try out some of those potential fixes you suggested today. In the meantime ill try sending those screenshots again

![MO2 Screenshot 1](https://github.com/FWDekker/fo4vr-modlist/assets/170687509/9847df78-bfd9-4cdf-baa8-bc4c3f52ba82)
![MO2 Screenshot 2](https://github.com/FWDekker/fo4vr-modlist/assets/170687509/50971a35-0662-4237-9b63-910873ce8237)
![MO2 Screenshot 3](https://github.com/FWDekker/fo4vr-modlist/assets/170687509/276b2d42-d6c8-4f5b-a957-9dead85d46ca)
![MO2 Screenshot 4](https://github.com/FWDekker/fo4vr-modlist/assets/170687509/c9517550-e067-4731-847c-41fb38dc3a05)

**Comment by FWDekker** [comment] 2024-05-25 15:03
Your screenshots indicate that the DLCs have not been activated. In the list of plugins on the right-hand side, scroll up, and enable the checkboxes for the DLCs.

**Comment by Psychogamer515** [comment] 2024-05-25 15:14
as far as i see all the boxes in the plugin list on the right are all checked. If you are talking about the last screenshot, i had the archives tab selected but i cant select any of the check boxes.

I tried your first suggestion and there is nothing different that i can see

Additionally i got this popup just before launching MO2 , i tried loading but it wouldn't launch unless i skipped.

![Screenshot 2024-05-25 110140](https://github.com/FWDekker/fo4vr-modlist/assets/170687509/37359e24-fe6e-4ece-a3b1-06a8236f8bea)

**Comment by FWDekker** [comment] 2024-05-25 15:32
That can't be right... unless you only copied the `.ba2` files of the non-VR FO4 DLC, but not the `.esm` files?

If you scroll all the way up in the list of plugins, you should see this:
![List of plugins, with FO4VR esms and non-VR FO4 DLC esms enabled.](https://github.com/FWDekker/fo4vr-modlist/assets/13442533/09e14c61-46dd-4abb-9ba1-41ec77734b88)

If any of those are not enabled, or if you're missing any, then something went wrong while copying the DLC, and I suggest you redo Section 2.3 of the guide.

**Comment by FWDekker** [comment] 2024-05-25 15:41
As for the error about `plugin_python`, I've never seen that before. After searching around a bit, I think it's either the result of a botched installation (for example, you upgraded MO2 from v2.4.4 to v2.5.0 without doing a clean install), or [it's a bug in MO2](https://github.com/ModOrganizer2/modorganizer/issues/1672). Either way, I'm not sure what the impact is. You can try using the [v2.5.1 RC2 pre-release of MO2](https://github.com/ModOrganizer2/modorganizer/releases/tag/v2.5.1rc2), though I haven't personally tried that version.

**Comment by Psychogamer515** [comment] 2024-05-25 17:00
I redid the steps from Sec 2.3 i copied and pasted the files into my fallout 4 vr data folder as well as the steam console thing. I'm not sure exactly how to enable the esm files. ill send a screenshot of my data folder to see if there's anything amiss that you can notice. 

Also, i really appreciate all the help that you've offered so far. Other people have just told me to not give up or that ill just figure it out but this stuff just kind of goes a little over my head.
![Fallout 4 VR Data SC 1](https://github.com/FWDekker/fo4vr-modlist/assets/170687509/191a96f3-c861-487c-bdeb-495c9193843a)

**Comment by FWDekker** [comment] 2024-05-25 17:32
I'm glad to help. I tried to make my guide as accessible as possible, so if someone doesn't understand something, that just means there's something I can explain better :-)

Your list of files looks complete and normal. I think the issue is that some ESMs in MO2 are not enabled. To enable them:

1. Go to your list of plugins in MO2. That's this list:
   ![List of plugins in MO2.](https://github.com/FWDekker/fo4vr-modlist/assets/13442533/6ed88e4d-8ff1-4f85-851d-6a5718f348e1)
   Each line in that list is a plugin. A plugin can be a DLC or a mod.
2. Scroll all the way up in the list. You know you're at the top when there's a `1` in the column for "Priority".
   This is the top of my list, for example. (My list contains a few plugins that you don't have. That's normal, don't worry about that.)
   ![The top of the list of plugins in MO2.](https://github.com/FWDekker/fo4vr-modlist/assets/13442533/6ee0faca-6b21-485b-85b8-73e958ce40ee)
3. All the way at the top of this list, you should have several plugins in bold. These plugins all end in `.esm`. Make sure all those bold plugins are enabled. A plugin is enabled if the checkbox to the left of the name is blue with a checkmark in it. If it's not enabled, click that checkbox. Again, make sure all `.esm` plugins (in bold) have that checkbox toggled on. Once you have that, I suspect your issues should be solved.

**Comment by Psychogamer515** [comment] 2024-05-25 21:53
Hey was out doing chores all day, 
So i see what your talking about with the imgs you sent. is there some way that you know of that i can get MO2 to recognize that i have those esms that were in that file, like i can link it in a way i guess, cause the only bold one that it recognizes is the sims settlements one.

My personal guess is that my computer sees the files but MO2 doesn't, feels like i'm grasping at straws though lol.

also saw that commit thing not sure what it is?

**Comment by FWDekker** [comment] 2024-05-25 22:58
The commit is there mostly for management reasons. When I described the changes in that commit, I referenced this issue that you opened, GitHub detected that, and shows it in the feed here. It's not something I expect you to look at per sé.

If the DLC's ESMs are not visible in MO2, but they are visible in File Explorer, then the most likely cause is that you have misconfigured MO2. To check and fix this, you can go to MO2's settings window, find the "Paths" tab, and check that the "Managed Game" path corresponds to where you're looking for the ESMs. Based on your earlier screenshot, the "Managed Game" path in MO2 should say `D:\Games\Steam\SteamLibrary\steamapps\common\Fallout 4 VR\Fallout4VR.exe`. If it says something else, well, we've found the issue. You can simply change that path in your MO2 settings, and I suspect your issues will be fixed. (But you may want to double-check that you didn't accidentally install F4SEVR and mods from Section 4.1 in the wrong directory either. And also check the MO2 run configuration you made for F4SEVR.)

**Comment by Psychogamer515** [comment] 2024-05-26 00:05
Ah so that's what a commit is thank you :)
![MO2 Screenshot 6](https://github.com/FWDekker/fo4vr-modlist/assets/170687509/19af33f1-5a6b-4bd2-b3e0-d319b83203b4)
As far as i can tell the managed games path seems correct but do you think should the base directory should be what it says?

**Comment by FWDekker** [comment] 2024-05-26 09:42
It took me a while to spot, but you have to look _really_ carefully at the paths.

In your earlier screenshot of File Explorer, your path is
`D:\Games\Steam\SteamLibrary\steamapps\common\Fallout 4 VR`.
In your screenshot of MO2's settings, your path is
`D:\Games\Steam\SteamLibrary\Steam\steamapps\common\Fallout 4 VR`.

It's very subtle, but removing that extra `Steam` in MO2's path should (hopefully) resolve your issue. You may also want to check that erroneous directory, to see if it really exists; if it turns out you have things installed twice, you can save a lot of disk space :P

**Comment by Psychogamer515** [comment] 2024-05-26 14:14
Thank you! I figured out that the correct file was in a separate directory that was similarly named, the esms are on my list FINALLY. do you think its safe to delete the extra stuff in the other directory? Instead of clicking the steam apps the first time i chose the steam folder just above and it had a very similar folder lineup afterwards. I'm gonna try out the game and see if it finally works.

**Comment by Psychogamer515** [comment] 2024-05-26 14:56
New issue it seems like the game wont even launch at all now got a new pop-up when trying to launch the game. This is what it looked like, any suggestions?
![MO2 Screenshot 7](https://github.com/FWDekker/fo4vr-modlist/assets/170687509/3ade5360-0476-4ee7-bde7-b32e8dea7a1a)

**Comment by FWDekker** [comment] 2024-05-26 16:09
Yes, you can probably safely delete the directory that MO2 is not using. But make sure that
1. Steam is not using that directory, by checking where Steam thinks FO4VR is installed (using the method described in my previous comment), and
2. check that the MO2 run configuration for F4SEVR uses the new directory as well.

As for the error you have now... I'm not sure what happened there? Could you try reinstalling (and thus overwriting) the [VR Address Library for F4SEVR](https://www.nexusmods.com/fallout4/mods/64879) mod? You should try both the latest version (v1.7.0) and the version I tested with (v1.6.1). I expect that both should work, but let me know which (if any) works.

**Comment by Psychogamer515** [comment] 2024-05-26 17:01
Does the directory have to be in the steam apps folder (D:\Games\Steam\SteamLibrary\steamapps\common\Fallout 4 VR)
 or can it be in the steam folder (D:\Games\Steam\SteamLibrary\Steam\steamapps\common\Fallout 4 VR) from before?

I saw that steam is pulling stuff directly from the steam folder when i right clicked the game in steam to see the file location. While everything I've been doing has been going into the steam apps folder where all the MO2 and other things ive been doing for the guide has been going. 

Do you think it would mess everything up if i tried copying all of my files to the directory that steam wants to pull from? It seems if i don't do that ill have to kind of start over but do everything properly into that file instead.

I'm not sure if its rude or improper to ask if we can get into a discord voice call while i screenshare and we kind of figure out whats going on.  If not thats perfectly fine

**Comment by FWDekker** [comment] 2024-05-26 17:39
I recommend that you use the folder that Steam thinks FO4VR is in. You don't need to do everything all over again, because the mods that you downloaded through MO2 are actually stored in MO2, so you don't need to reinstall them; just fix the "Managed Game" path in MO2 and you should be fine. The only mods that you need to reinstall are those from Section 4.1.

In short, I suggest you choose to use the folder used by Steam, and then (in the following order!)
1. move (don't copy, move is way faster than copy; move is also known as "cut") the DLC files from the incorrect directory to the correct directory,
2. verify integrity of game files,
3. delete the incorrect directory,
4. reinstall mods from Section 4.1, but now into the right directory, (and make sure you follow all installation steps again),
5. fix the "Managed Game" path in MO2,
6. check the path of the F4SEVR run configuration in MO2.

And after that, you should be set.

I think you can do these steps just fine, so I recommend that you try them, but if you still get stuck, I'm fine with voice chat, so let me know if that is the case. You can email me your Discord name ([see my GitHub profile to find my email address](https://github.com/FWDekker)) and I'll add you then :-)

**Comment by FWDekker** [comment] 2024-07-28 09:14
Hiya! I'll close this issue, but if you have further questions or remarks, you know how to contact me on Discord :-)

**Closed by FWDekker** 2024-07-28 09:14 UTC
Labels: troubleshooting
